New coding standard
zendframework/zend-test pull request #39
Opened 2016-11-13 20:04 UTC by Koopzington

Usage of the newly introduced zendframework/zend-coding-standard for CS checks.

2017-02-04 21:44 UTC, froschdesign approved these changes

2017-02-05 11:34 UTC, samsonasik requested changes

2017-02-05 11:34 UTC, samsonasik commented on composer.json
> +        "phpunit/phpunit": "^4.6 || ^5.0"
phpunit should in require path to manage syntax compat, also, use phpunit ^5.6 || ^6.0 in favor of https://github.com/zendframework/zend-test/pull/43

2017-02-05 11:39 UTC, samsonasik commented on composer.json
> +        "phpunit/phpunit": "^4.6 || ^5.0"
I meant, phpunit ^5.7 || ^6.0

2017-02-05 13:11 UTC, froschdesign requested changes

2017-02-05 13:11 UTC, froschdesign commented on composer.json
> +        "phpunit/phpunit": "^4.6 || ^5.0"
PHPUnit is required in this component,

2017-02-05 18:53 UTC, samsonasik commented
move phpunit to "require" section in composer.json, also, this should belongs to develop branch, after it pointed to develop, please rebase agains develop.

2017-02-05 19:05 UTC, Koopzington commented
https://github.com/zendframework/zend-mail/pull/121
every other PR regarding the coding standard was against master, why should we do it differently in this case?

2017-02-05 19:13 UTC, samsonasik commented
upping phpunit was went to develop, and I think goes to master without coding fix will go bugs, please check #43 for the phpunit 5 & 6 compat fix

2017-02-05 19:45 UTC, Koopzington commented
not entirely sure but i think i just screwed up, didn't i?

2017-02-05 19:52 UTC, samsonasik commented
You can do with the following steps:

```
git checkout develop
git pull git@github.com:zendframework/zend-test.git develop
git checkout new-coding-standard
git rebase develop
```

at this stage, you can fixes the conflicts (don't commit), then do

```
git add .
git rebase --continue
```

Next, do force push:

```
git push --force origin new-coding-standard
```

Lastly, point the PR to develop branch via "Edit" button in PR title, select "base" branch to develop.

2017-02-05 22:22 UTC, Koopzington commented
seems to look good now

2017-02-06 01:44 UTC, samsonasik commented on .travis.yml
>          - DEPS=latest
remove "DEPS=latest" from php: 5.6 entry:
```
    - php: 5.6
      env:
        - DEPS=latest
```
as php 5.6 can't install phpunit 6

2017-02-06 01:46 UTC, samsonasik commented on .travis.yml
>          - DEPS=latest
check modified .travis at https://raw.githubusercontent.com/samsonasik/zend-test/0b0bf0f351e228557997edac539352a1d5932be5/.travis.yml that applied at PR #43

2017-02-07 22:33 UTC, samsonasik commented on .travis.yml
> +  - if [[ $TEST_COVERAGE == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi
`--no-update` make it not install anything php-coveralls bin, change with include $COMPOSER_ARGS and remove the `--no-update` like the following :

```yaml
- if [[ $TEST_COVERAGE == 'true' ]]; then composer require --dev satooshi/php-coveralls $COMPOSER_ARGS; fi
```

2017-02-07 22:34 UTC, samsonasik commented on .travis.yml
> +  - if [[ $TEST_COVERAGE == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi
see https://github.com/zendframework/zend-test/pull/43/commits/226100a02e231dc12fe0f8e52e97434ba6587531

2017-02-07 23:55 UTC, samsonasik commented on .travis.yml
> +  - if [[ $TEST_COVERAGE == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi
need to be re-add as @webimpress  suggestion at https://github.com/zendframework/zend-test/pull/43#discussion_r99944201

2017-02-07 23:56 UTC, samsonasik commented on .travis.yml
>          - DEPS=latest
need to be re-add as @webimpress suggestion at #43 (comment)

2017-02-08 07:55 UTC, Koopzington commented on .travis.yml
> +  - if [[ $TEST_COVERAGE == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi
Can we please stop abusing this PR for changes which weren't intended with it?
See #35

2017-02-08 11:23 UTC, samsonasik commented on .travis.yml
> +  - if [[ $TEST_COVERAGE == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi
I'm sorry for it, just make sure if your PR merged first, the coveralls command will still works, nothing else.

2017-05-01 19:09 UTC, weierophinney commented on composer.json
> +        "phpunit/phpunit": "^5.7 || ^6.0",
We need to keep 4.0 support for BC purposes at this point. That version still works with all versions of PHP; however, there's syntax from v4 that doesn't work later, which would mean that upping the PHPUnit version could break existing tests for people using this component.

I'll revert this on merge.

2017-05-01 19:17 UTC, merged