Provid a mechanism to check if we need to restore global var
zendframework/zend-test pull request #73
Opened 2018-12-13 11:26 UTC by fezfez

Hello,

Here is the patch to prevent #72 issue.

2018-12-13 11:27 UTC, Ocramius requested changes

2018-12-13 11:27 UTC, Ocramius commented on src/PHPUnit/Controller/AbstractControllerTestCase.php
> +    private $isOriginalEnvironmentPreserved = false;
I don't think this should be configurable at all

2018-12-13 11:29 UTC, fezfez commented
@Ocramius : The Unit tests is not working as expected, i check that

2018-12-13 11:30 UTC, Ocramius commented
One note here: I think the original mistake that causes https://github.com/zendframework/zend-test/issues/72 and https://github.com/zendframework/zend-test/issues/71 is coming from https://github.com/zendframework/zend-test/pull/66. One of the ideas behind the design of ZF2 (and now newer versions) was to never modify the operating environment of downstream consumers, and we've broken that. 

@webimpress can you maybe check this as well? There should be a different solution that can replace #66.

2018-12-13 11:33 UTC, webimpress commented
@Ocramius Sure, I'll have on it today afternoon. I see clearly there is some issue, but I have completely forgotten why I have done that fix...

2018-12-13 11:34 UTC, fezfez commented
@Ocramius : test now work as expected and the attribute is now protected

2018-12-13 18:23 UTC, michalbundyra commented
@Ocramius The easiest way is to xdebug tests I've added in #66.
The solution I've applied is copied from zend-http, we are doing it there in several tests.
The "source problem" is here:
https://github.com/zendframework/zend-http/blob/bdfe6ca648829c681c20323f49071fbe645caa7e/src/PhpEnvironment/Request.php#L476-L542
where we are using values from `$_SERVER` to determine the path/base url. And as `phpunit` is a runner, this is why we had problem with this value in a request path.

Thoughts?

2018-12-14 05:03 UTC, Ocramius commented
What we could probably do is provide a utility to back up/restore values, rather than resetting them upfront.

2018-12-14 07:56 UTC, webimpress commented
Hm... How do you mean? You want someone manually "reset them" if they are using "phpunit" parameter in the query/path? I was checking if we can do it somehow on dispatch, but I can't see any clear and nice solution right now.

As I noted in my PR, I wasn't sure if it is the best solution and what impact it's gonna have. It works for us, but as we see, not for everyone...

2019-01-08 17:02 UTC, weierophinney commented
Closing in favor of #74.

2019-01-08 17:02 UTC, closed without merging